package com.darkere.crashutils.Screens.Types;

public enum DropDownType {
    RENDERTYPES,
    TICKETS,
    ENTITIES,
    TILEENTITIES,
    SELECTOR,
    ENTITYCHUNKLIST,
    TILEENTITYCHUNKLIST,
    TICKETLIST,
    LOCATIONS,
    LOCATIONCHUNKLIST,
    TICKETCOUNTLIST,
    STATECOUNTLIST,
    PLAYERLIST
}
